import { randomBytes } from 'node:crypto';
import {
  API_REQUIRED_ENVIRONMENT_VARIABLES,
  CREDENTIAL_ENVIRONMENT_VARIABLES,
  assertSecureEnvironment,
  isKnownPublicExampleCredential,
} from '../api_backend/lib/environmentPolicy';
import type { RelayCertificateFiles } from './relay-certificates';

type Environment = Readonly<Record<string, string | undefined>>;

export const NATIVE_DEBUG_REQUIRED_ENVIRONMENT_VARIABLES = [
  ...API_REQUIRED_ENVIRONMENT_VARIABLES,
  'SERVICE_KEY',
  'RMM_SERVER_API_KEY',
  'RMM_TELEMETRY_SERVICE_KEY',
  'TALOS_AI_RUNNER_SERVICE_KEY',
] as const;

export const NATIVE_DEBUG_REQUIRED_CORS_ORIGINS = [
  'http://localhost:3000',
  'http://127.0.0.1:3000',
  'https://dev.talos.cloud',
] as const;

const PERSISTED_NATIVE_DEBUG_SECRET_VARIABLES = [
  'JWT_SECRET',
  'APP_ENCRYPTION_KEY',
  'SERVICE_KEY',
  'RMM_SERVER_API_KEY',
  'RMM_TELEMETRY_SERVICE_KEY',
  'TALOS_AI_RUNNER_SERVICE_KEY',
  'RMM_AGENT_TOKEN',
] as const;

type PersistedNativeDebugSecret = (typeof PERSISTED_NATIVE_DEBUG_SECRET_VARIABLES)[number];

export type NativeDebugCredentialResolution = {
  environment: Record<string, string | undefined>;
  persistedSecrets: Partial<Record<PersistedNativeDebugSecret, string>>;
  repairedVariables: string[];
};

function usableCredential(value: string | undefined): string | undefined {
  const trimmed = value?.trim();
  return trimmed && !isKnownPublicExampleCredential(trimmed) ? trimmed : undefined;
}

function newNativeDebugSecret(variable: PersistedNativeDebugSecret): string {
  const purpose = variable.toLowerCase();
  return `talos_debug_${purpose}_${randomBytes(32).toString('base64url')}`;
}

/**
 * Resolve local-only credentials for the native debug stack without weakening the shared startup
 * policy. Valid operator values always win. Missing required values and published example markers
 * are replaced by stable secrets from the ignored debug-secret file, or generated once when that
 * file has no usable value.
 */
export function resolveNativeDebugCredentials(
  configuredEnvironment: Environment,
  storedDebugSecrets: Environment,
): NativeDebugCredentialResolution {
  const environment = { ...configuredEnvironment };
  const persistedSecrets: Partial<Record<PersistedNativeDebugSecret, string>> = {};
  const repairedVariables = new Set<string>();

  for (const variable of PERSISTED_NATIVE_DEBUG_SECRET_VARIABLES) {
    const stored = usableCredential(storedDebugSecrets[variable]);
    if (stored) persistedSecrets[variable] = stored;
  }

  const ensurePersisted = (variable: PersistedNativeDebugSecret): string => {
    const configured = usableCredential(environment[variable]);
    if (configured) return configured;

    const replacement = persistedSecrets[variable] ?? newNativeDebugSecret(variable);
    persistedSecrets[variable] = replacement;
    environment[variable] = replacement;
    repairedVariables.add(variable);
    return replacement;
  };

  for (const variable of [
    'JWT_SECRET',
    'APP_ENCRYPTION_KEY',
    'SERVICE_KEY',
    'RMM_SERVER_API_KEY',
    'RMM_TELEMETRY_SERVICE_KEY',
    'TALOS_AI_RUNNER_SERVICE_KEY',
  ] as const) {
    ensurePersisted(variable);
  }

  if (environment.APP_ENCRYPTION_KEY === environment.JWT_SECRET) {
    let replacement = usableCredential(storedDebugSecrets.APP_ENCRYPTION_KEY);
    if (!replacement || replacement === environment.JWT_SECRET) {
      replacement = newNativeDebugSecret('APP_ENCRYPTION_KEY');
    }
    persistedSecrets.APP_ENCRYPTION_KEY = replacement;
    environment.APP_ENCRYPTION_KEY = replacement;
    repairedVariables.add('APP_ENCRYPTION_KEY');
  }

  for (const variable of CREDENTIAL_ENVIRONMENT_VARIABLES) {
    if (!isKnownPublicExampleCredential(environment[variable])) continue;

    if (variable === 'API_SERVICE_KEY') {
      environment.API_SERVICE_KEY = environment.SERVICE_KEY;
    } else if (variable === 'TALOS_AI_RUNNER_RMM_SERVER_KEY') {
      environment.TALOS_AI_RUNNER_RMM_SERVER_KEY = environment.RMM_SERVER_API_KEY;
    } else if (variable === 'RMM_AGENT_TOKEN') {
      ensurePersisted('RMM_AGENT_TOKEN');
    } else if (variable === 'OPENAI_API_KEY') {
      delete environment.OPENAI_API_KEY;
    }
    repairedVariables.add(variable);
  }

  return {
    environment,
    persistedSecrets,
    repairedVariables: [...repairedVariables].sort(),
  };
}

export function serializeNativeDebugSecrets(
  secrets: Readonly<Partial<Record<PersistedNativeDebugSecret, string>>>,
): string {
  const assignments = PERSISTED_NATIVE_DEBUG_SECRET_VARIABLES.flatMap((variable) => {
    const value = secrets[variable];
    return value ? [`${variable}=${value}`] : [];
  });
  if (assignments.length === 0) return '';

  return [
    '# Generated by bun run debug. Local only; never commit or share this file.',
    '# Valid values from apps/.env, api_backend/.env, or the shell take precedence.',
    ...assignments,
    '',
  ].join('\n');
}

export function assertNativeDebugEnvironment(environment: Environment): void {
  assertSecureEnvironment(
    environment,
    NATIVE_DEBUG_REQUIRED_ENVIRONMENT_VARIABLES,
    'Native debug stack',
  );
}

export function mergeDebugEnvironment(
  appsEnvironment: Environment,
  apiEnvironment: Environment,
  shellEnvironment: Environment,
): Record<string, string | undefined> {
  return {
    ...appsEnvironment,
    ...apiEnvironment,
    ...shellEnvironment,
  };
}

export function resolveNativeDebugCorsAllowedOrigins(environment: Environment): string {
  const configuredOrigins = (environment.CORS_ALLOWED_ORIGINS ?? environment.FRONTEND_URL ?? '')
    .split(',')
    .map((origin) => origin.trim())
    .filter(Boolean);

  return [...new Set([...configuredOrigins, ...NATIVE_DEBUG_REQUIRED_CORS_ORIGINS])].join(',');
}

export function withNativeRelayCertificates(
  environment: Environment,
  relayCertificates: RelayCertificateFiles,
): Record<string, string | undefined> {
  return {
    ...environment,
    RMM_RELAY_TLS_TERMINATED: 'false',
    RMM_RELAY_TLS_CERT_PATH: relayCertificates.certificateFile,
    RMM_RELAY_TLS_KEY_PATH: relayCertificates.keyFile,
  };
}

/**
 * Keep host-native debug processes deterministic across local shell and Docker Desktop settings.
 * Redpanda must advertise the IPv4 address that its loopback-only published port is bound to;
 * advertising `localhost` can resolve to IPv6 first and make metadata discovery fail intermittently.
 */
export function withNativeDebugProcessEnvironment(
  environment: Environment,
): Record<string, string | undefined> {
  const resolved: Record<string, string | undefined> = {
    ...environment,
    FORCE_COLOR: '1',
    TALOS_REDPANDA_ADVERTISED_HOST: '127.0.0.1',
  };
  delete resolved.NO_COLOR;
  return resolved;
}

export function resolveDebugRelayUrl(environment: Environment, fallback: string): string {
  return environment.RMM_RELAY_URL?.trim() || fallback;
}

export function resolveDebugJwtSecret(environment: Environment): string {
  const configured = environment.JWT_SECRET?.trim();
  if (configured) return configured;
  return `talos_debug_jwt_${randomBytes(32).toString('base64url')}`;
}
