[package]
name = "talos_log_util"
version = "0.1.4"
edition = "2021"
rust-version.workspace = true
license.workspace = true

[dependencies]
chrono = { version = "0.4", default-features = false, features = ["clock"] }
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
zip = { version = "8.0.0", default-features = false, features = ["deflate"] }

[lints]
workspace = true
