[package]
name = "talos_supervisor"
version = "0.5.33"
edition = "2021"
rust-version.workspace = true
license.workspace = true
build = "build.rs"

[dependencies]
anyhow = "1.0"
talos_update_common = { path = "../talos_update_common" }
talos_protocol = { path = "../talos_protocol" }
talos_log_util = { path = "../talos_log_util" }
reqwest = { version = "0.12", default-features = false, features = ["macos-system-configuration", "rustls-tls", "rustls-tls-native-roots", "system-proxy"] }
serde_json = "1"
tokio = { version = "1.39", features = ["macros", "rt", "time"] }
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
walkdir = "2.5.0"
zip = { version = "8.0.0", default-features = false, features = ["deflate"] }

[target.'cfg(windows)'.dependencies]
windows-service = "0.8"
windows-sys = { version = "0.61.2", features = ["Win32_Foundation", "Win32_Security_Cryptography", "Win32_Security_WinTrust", "Win32_System_Registry", "Win32_System_Threading"] }

[build-dependencies]
winres = "0.1.12"

[lints]
workspace = true
