[package]
name = "talos_viewer_updater"
version = "0.5.15"
edition = "2021"
rust-version.workspace = true
license.workspace = true
build = "build.rs"

[dependencies]
anyhow = "1.0"
talos_protocol = { path = "../talos_protocol" }
talos_log_util = { path = "../talos_log_util" }
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
walkdir = "2.5.0"
zip = { version = "8.0.0", default-features = false, features = ["deflate"] }

[target.'cfg(windows)'.dependencies]
windows-sys = { version = "0.61.2", features = ["Win32_Foundation", "Win32_System_Threading"] }

[build-dependencies]
winres = "0.1.12"

[lints]
workspace = true
